name: deployment.yml
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4.2.2
      - name: build docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/edify-app:ubuntu-latest .
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to docker hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/edify-app:ubuntu-latest 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pull the docker image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/edify-app:latest
      - name: Run container
        run: docker container run -dt --name edify -p 80:80  ${{ vars.DOCKER_USERNAME }}/edify-app:latest
      - name: list container
        run: docker container ls -a 
         
    


